FROM python:slim

ARG STATICJINJAPLUS_VERSION

WORKDIR /app

ADD https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${STATICJINJAPLUS_VERSION}.tar.gz /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz

RUN python3 -m venv /venv
RUN /venv/bin/pip install -r requirements.txt

COPY . .